/* Generated by Stella. Requires the scalar runtime and C/GC ABI v1. */
#include <stella/runtime.h>
#include <stella/gc.h>
#include <stella/program.h>
#include <stella/scalar.h>
#include <stella/host.h>
const enum StellaScalarKind stella_program_argument_kind = STELLA_SCALAR_NAT;
const enum StellaScalarKind stella_program_result_kind = STELLA_SCALAR_NAT;

static const StellaObjectDescriptor stella_data_nil_descriptor = {
  .abi_version = STELLA_C_GC_ABI_VERSION, .kind = STELLA_OBJECT_DATA,
  .flags = STELLA_DESCRIPTOR_STATIC, .entry_arity = 0,
  .managed_count = 0, .primitive_count = 0, .slot_capacity = 0,
  .entry_code = NULL, .debug_name = "stella_data_nil"
};
static StellaObject stella_data_nil = {
  .descriptor = &stella_data_nil_descriptor, .gc_word = 0, .fields = NULL
};

static const StellaObjectDescriptor stella_data_cons_descriptor = {
  .abi_version = STELLA_C_GC_ABI_VERSION, .kind = STELLA_OBJECT_DATA,
  .flags = 0, .entry_arity = 0,
  .managed_count = 2, .primitive_count = 0, .slot_capacity = 2,
  .entry_code = NULL, .debug_name = "stella_data_cons"
};

static const StellaObjectDescriptor stella_data_reference_descriptor = {
  .abi_version = STELLA_C_GC_ABI_VERSION, .kind = STELLA_OBJECT_DATA,
  .flags = 0, .entry_arity = 0,
  .managed_count = 1, .primitive_count = 0, .slot_capacity = 1,
  .entry_code = NULL, .debug_name = "stella_data_reference"
};

static void stella_fn_0(StellaValue *result_root, StellaValue *self_root, size_t argument_count, StellaValue *const argument_roots[]);
static const StellaObjectDescriptor stella_fn_0_descriptor = {
  .abi_version = STELLA_C_GC_ABI_VERSION, .kind = STELLA_OBJECT_CLOSURE,
  .flags = STELLA_DESCRIPTOR_STATIC, .entry_arity = 1,
  .managed_count = 0, .primitive_count = 0, .slot_capacity = 0,
  .entry_code = stella_fn_0, .debug_name = "stella_fn_0"
};
static StellaObject stella_fn_0_closure = {
  .descriptor = &stella_fn_0_descriptor, .gc_word = 0, .fields = NULL
};

static void stella_fn_1(StellaValue *result_root, StellaValue *self_root, size_t argument_count, StellaValue *const argument_roots[]);
static const StellaObjectDescriptor stella_fn_1_descriptor = {
  .abi_version = STELLA_C_GC_ABI_VERSION, .kind = STELLA_OBJECT_CLOSURE,
  .flags = STELLA_DESCRIPTOR_STATIC, .entry_arity = 1,
  .managed_count = 0, .primitive_count = 0, .slot_capacity = 0,
  .entry_code = stella_fn_1, .debug_name = "stella_fn_1"
};
static StellaObject stella_fn_1_closure = {
  .descriptor = &stella_fn_1_descriptor, .gc_word = 0, .fields = NULL
};

static void stella_fn_0(StellaValue *result_root, StellaValue *self_root, size_t argument_count, StellaValue *const argument_roots[]) {
  if (result_root == NULL || self_root == NULL || *self_root == NULL ||
      *self_root != &stella_fn_0_closure ||
      argument_count != 1 || argument_roots == NULL ||
      argument_roots[0] == NULL || *argument_roots[0] == NULL) {
    stella_abi_violation("invalid generated function entry");
  }
  StellaValue slots[7] = {NULL};
  for (size_t i = 0; i < 7; ++i) stella_gc_push_root(&slots[i]);
  if ((*argument_roots[0]) == &stella_data_nil) {
    slots[1] = &stella_nat_zero;
    slots[0] = slots[1];
  }
  else if ((*argument_roots[0])->descriptor == &stella_data_cons_descriptor) {
    slots[2] = stella_gc_read_managed(argument_roots[0], 0);
    slots[3] = stella_gc_read_managed(argument_roots[0], 1);
    slots[4] = &stella_fn_0_closure;
    {
      StellaValue *arguments[] = {&slots[3]};
      slots[4]->descriptor->entry_code(&slots[5], &slots[4], 1, arguments);
    }
    slots[6] = stella_gc_alloc(&stella_nat_succ_descriptor);
    stella_object_init_managed(slots[6], 0, slots[5]);
    slots[0] = slots[6];
  }
  else {
    stella_abi_violation("invalid match constructor");
  }
  *result_root = slots[0];
  for (size_t i = 7; i > 0; --i) stella_gc_pop_root(&slots[i - 1]);
}

static void stella_fn_1(StellaValue *result_root, StellaValue *self_root, size_t argument_count, StellaValue *const argument_roots[]) {
  if (result_root == NULL || self_root == NULL || *self_root == NULL ||
      *self_root != &stella_fn_1_closure ||
      argument_count != 1 || argument_roots == NULL ||
      argument_roots[0] == NULL || *argument_roots[0] == NULL) {
    stella_abi_violation("invalid generated function entry");
  }
  StellaValue slots[14] = {NULL};
  for (size_t i = 0; i < 14; ++i) stella_gc_push_root(&slots[i]);
  slots[0] = &stella_data_nil;
  slots[1] = stella_gc_alloc(&stella_data_reference_descriptor);
  stella_object_init_managed(slots[1], 0, slots[0]);
  slots[2] = (*argument_roots[0]);
  slots[3] = &stella_unit;
  slots[4] = slots[3];
  slots[5] = &stella_nat_zero;
  while (slots[2] != &stella_nat_zero) {
    if (slots[2]->descriptor != &stella_nat_succ_descriptor) {
      stella_abi_violation("invalid recursor count");
    }
    slots[6] = stella_gc_read_managed(&slots[1], 0);
    slots[7] = stella_gc_alloc(&stella_data_cons_descriptor);
    stella_object_init_managed(slots[7], 0, slots[5]);
    stella_object_init_managed(slots[7], 1, slots[6]);
    stella_gc_write_managed(&slots[1], 0, &slots[7]);
    slots[8] = &stella_unit;
    slots[4] = slots[8];
    slots[9] = stella_gc_alloc(&stella_nat_succ_descriptor);
    stella_object_init_managed(slots[9], 0, slots[5]);
    slots[5] = slots[9];
    slots[10] = stella_gc_read_managed(&slots[2], 0);
    slots[2] = slots[10];
  }
  slots[11] = &stella_fn_0_closure;
  slots[12] = stella_gc_read_managed(&slots[1], 0);
  {
    StellaValue *arguments[] = {&slots[12]};
    slots[11]->descriptor->entry_code(&slots[13], &slots[11], 1, arguments);
  }
  *result_root = slots[13];
  for (size_t i = 14; i > 0; --i) stella_gc_pop_root(&slots[i - 1]);
}

void stella_program_entry(StellaValue *result_root, StellaValue *argument_root) {
  if (result_root == NULL || argument_root == NULL || result_root == argument_root ||
      *result_root != NULL || *argument_root == NULL) {
    stella_abi_violation("invalid program-entry roots");
  }
  StellaValue self = &stella_fn_1_closure;
  stella_gc_push_root(&self);
  StellaValue *arguments[] = {argument_root};
  stella_fn_1(result_root, &self, 1, arguments);
  stella_gc_pop_root(&self);
}
